### ISSUE TITLE
FunctionSpacing sniff misconfigured

### ISSUE THREAD

**Issue by janedbal** [consistence/coding-standard#7]
What is the reason for excluding `Squiz.WhiteSpace.FunctionSpacing.After` [here](https://github.com/consistence/coding-standard/blob/ddecaafc8ab11281c13b01d7c2a97d4b9e31d12b/Consistence/ruleset.xml#L122)? With this, you can separate methods by any number of empty lines. May I send PR removing this exclusion?

**Comment by VasekPurchart** [comment]
Thanks for reminding me of this, I wanted to improve this long time ago, but have not gotten around to do it.

The reason is mentioned in the comment after the exclude. I have reported this to the PHPCodeSniffer repo https://github.com/squizlabs/PHP_CodeSniffer/issues/1075 and you can see an exact code example there.

I am closing this now and when/if the issue gets fixed I will turn the rule back on in this ruleset. as I did for example with https://github.com/squizlabs/PHP_CodeSniffer/issues/794 in this [commit](https://github.com/consistence/coding-standard/commit/d7d68c4f0eb9aef72702b6caa65756c6c517a60b#diff-6b0a0452d0233d878cb89d14e06152d8L43).

If the described behavior is no issue for you feel free to override this in your ruleset in the meantime (this ruleset should be a solid foundation, but is meant to be extended - that is why I am trying to always mention why something was excluded.

**Comment by janedbal** [comment]
Thanks for clarification and creating issue in codesniffer repo, but how can I override already excluded rule? I didn't find any way to re-include it.

**Comment by ondrejmirtes** [comment]
By resetting severity example from Consistence ruleset.xml):

```
<rule ref="Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines">
    <severity>5</severity><!-- turned off by PSR2 -> turning on with default severity -->
</rule>
```

**Comment by VasekPurchart** [comment]
Thanks Ondra, just had copied the same example in my clipboard :)
